#![feature(if_let_guard)]
//! All core `pt` functionality ìs available as a library. This primarily consists of parsing and
//! report / code generation.
//!
//! Main entry point is `TestSuite`
use base_traits::AsStr;
use indexmap::IndexMap;
use ruff_python_ast::Stmt;
use ruff_python_parser::{ParseError, parse_module};

mod failures;
pub use failures::{PyError, Traceback};

mod pytests;
pub use pytests::{TestDetails, TestStatus};

use crate::pytests::PythonTest;

/// A suite of tests from a single python source file.
///
/// Usage:
/// ```rust
/// use pt::TestSuite;
/// let src = String::from("def test_passes():\n    assert True\n");
///
/// // Parse python source to generate a TestSuite
/// let mut tests = TestSuite::try_from(src).unwrap();
///
/// // Generate a test runner to run with python
/// let runner = tests.runner("RUNNER_1");
///
/// // Update the test status with the output from the runner
/// tests.update_status("RUNNER_1", "RUNNER_1 test_passes PASS\n");
///
/// // Generate a summary execution report
/// let summary = tests.summary_report();
/// assert_eq!("test_passes PASS\n", summary)
/// ```
#[derive(Debug, Default, PartialEq)]
pub struct TestSuite {
    src: String,
    /// indexed by test name, retains ordering from original python source
    pub tests: IndexMap<String, TestDetails>,
}

impl TryFrom<String> for TestSuite {
    type Error = ParseError;
    fn try_from(src: String) -> Result<Self, Self::Error> {
        let tests: IndexMap<String, TestDetails> = parse_module(&src)?
            .into_suite()
            .into_iter()
            .filter_map(|stmt| -> Option<(String, TestDetails)> {
                match stmt {
                    Stmt::FunctionDef(function) if function.name.as_str().starts_with("test_") => {
                        Some((function.name.to_string(), function.into()))
                    }
                    _ => None,
                }
            })
            .collect();
        Ok(Self { src, tests })
    }
}

impl TestSuite {
    /// Generate a test runner which can be run with python and will execute all the tests.
    /// `id` is a unique ID which will be used in the output generated by python when executing the runner.
    pub fn runner<ID: AsRef<str>>(&self, id: ID) -> String {
        let mut test_runner = self.src.clone();
        test_runner.push_newline();
        test_runner.push_newline();
        test_runner.push_python_line(0, ["if __name__ == \"__main__\":"]);
        test_runner.push_python_line(1, ["from traceback import TracebackException"]);
        test_runner.push_python_line(1, ["import sys"]);
        self.tests.keys().for_each(|testname| {
            test_runner.push_newline();
            test_runner.push_python_line(1, ["print(\"", id.as_ref(), " ", testname, " RUNNING\")"]);
            test_runner.push_python_line( 1, ["try:"]);
            test_runner.push_python_line( 2, [testname, "()"]);
            test_runner.push_python_line( 1, ["except Exception:"]);
            test_runner.push_python_line(2,["TracebackException.from_exception(sys.exception(), capture_locals=True).print(file=sys.stdout)"]);
            test_runner.push_python_line(2,["print(\"", id.as_ref(), " ", testname, " FAIL\")"]);
            test_runner.push_python_line(1, ["else:"]);
            test_runner.push_python_line(2,["print(\"", id.as_ref(), " ", testname, " PASS\")"]);
        });
        test_runner
    }

    /// Returns a PythonTest with non-mutable references to both the full python source text and the
    /// test details.
    pub fn test<'suite, 'name>(
        &'suite self,
        testname: &'name str,
    ) -> Option<PythonTest<'name, 'suite, '_>> {
        let testdetails = self.tests.get(testname)?;
        Some(PythonTest {
            testname,
            full_src: &self.src,
            test_ast: &testdetails.ast,
            status: &testdetails.status,
        })
    }

    pub fn tests(&'_ self) -> impl Iterator<Item = PythonTest<'_, '_, '_>> {
        self.tests.iter().map(|(testname, testdetails)| PythonTest {
            testname,
            full_src: &self.src,
            test_ast: &testdetails.ast,
            status: &testdetails.status,
        })
    }

    /// Parse the output generated by executing the code from `runner()` and update status of all tests
    pub fn update_status(&mut self, id: &str, stdout: &str) {
        let mut tb_buf = String::new();
        for line in stdout.lines() {
            let mut words = line.split_whitespace();
            match words.next() {
                Some(id_) if id_ == id => {
                    let testname = words.next().unwrap();
                    let test = self.tests.get_mut(testname).unwrap();
                    let status = words.next().unwrap();
                    test.status = (status, tb_buf.as_str()).into();
                    tb_buf.clear();
                }
                Some(_) => {
                    tb_buf.push_line(0, [line]);
                }
                None => {
                    todo!("Make update_status fallible")
                }
            }
        }
    }

    /// List all tests with status, then provide failure reports for all failed tests.
    pub fn summary_report(&self) -> String {
        let mut summary = String::new();
        let mut details = String::new();
        for pytest in self.tests() {
            summary.push_line(0, [pytest.testname, " ", pytest.status.as_str()]);
            if let Some(report) = pytest.report() {
                details.push_newline();
                details.push_str(&report);
            }
        }
        summary.push_str(&details);
        summary
    }
}

/// For incrementally generating Strings.
///
/// - Initialise with `let mut str_buf = String::(new);`
/// - Reset (contents, not capacity) with `str_buf.clear();`
/// - Extend with `push_...` functions
trait StringBuffer {
    fn push_line<'strs>(&mut self, indent: usize, contents: impl IntoIterator<Item = &'strs str>);
    fn push_python_line<'strs>(
        &mut self,
        indent: usize,
        contents: impl IntoIterator<Item = &'strs str>,
    );
    fn push_newline(&mut self);
}

impl StringBuffer for String {
    fn push_newline(&mut self) {
        self.push('\n');
    }

    /// `indent` with spaces, concatenate `contents`, end with `\n`
    fn push_line<'strs>(&mut self, indent: usize, contents: impl IntoIterator<Item = &'strs str>) {
        for _ in 0..indent {
            self.push(' ');
        }
        for text in contents {
            self.push_str(text);
        }
        self.push_newline();
    }

    /// `indent` with 4 x n spaces, concatenate `contents`, end with `\n`
    fn push_python_line<'strs>(
        &mut self,
        indent: usize,
        contents: impl IntoIterator<Item = &'strs str>,
    ) {
        self.push_line(4 * indent, contents);
    }
}

#[derive(Debug, PartialEq, Eq, PartialOrd, Ord)]
enum Location {
    Position(usize),
    Line(usize),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn one_test() {
        let src = r"def test_passes():
    assert True
";
        let pytests: TestSuite = src.to_string().try_into().unwrap();
        assert_eq!(1, pytests.tests.len());
        assert!(pytests.tests.contains_key("test_passes"));
    }

    #[test]
    fn import_and_two_tests() {
        let src = r"import pathlib


def test_fails():
    assert False


def test_passes():
    assert True
";
        let pytests: TestSuite = src.to_string().try_into().unwrap();
        assert_eq!(2, pytests.tests.len());
        assert!(pytests.tests.contains_key("test_fails"));
        assert!(pytests.tests.contains_key("test_passes"));
    }
}
