#![feature(if_let_guard)]
//! All core `pt` functionality ìs available as a library. This primarily consists of parsing and
//! report / code generation.
//!
//! Main entry point is `TestSuite`
use base_traits::AsStr;
use indexmap::IndexMap;
use ruff_python_ast::Stmt;
use ruff_python_parser::{ParseError, parse_module};
use std::str::FromStr;

mod failures;
use crate::failures::TracebackLine;
pub use failures::{PyError, Traceback};

mod pytest;
pub use pytest::{Pytest, TestStatus};

/// A suite of tests from a single python source file.
///
/// Usage:
/// ```rust
/// use pt::TestSuite;
/// let src = "def test_passes():\n    assert True\n";
///
/// // Parse python source to generate a TestSuite
/// let mut tests = TestSuite::try_from(src).unwrap();
///
/// // Generate a test runner to run with python
/// let runner = tests.runner("RUNNER_1");
///
/// // Update the test status with the output from the runner
/// tests.update_status("RUNNER_1", "RUNNER_1 test_passes PASS\n");
///
/// // Generate a summary execution report
/// let summary = tests.summary_report();
/// assert_eq!("test_passes PASS\n", summary)
/// ```
#[derive(Debug, PartialEq)]
pub struct TestSuite {
    src: String,
    /// indexed by test name, retains ordering from original python source
    pub tests: IndexMap<String, Pytest>,
}

impl TryFrom<&str> for TestSuite {
    type Error = ParseError;
    fn try_from(src: &str) -> Result<Self, Self::Error> {
        let tests: IndexMap<String, Pytest> = parse_module(src)?
            .into_suite()
            .into_iter()
            .filter_map(|stmt| -> Option<(String, Pytest)> {
                match stmt {
                    Stmt::FunctionDef(function) if function.name.as_str().starts_with("test_") => {
                        Some((function.name.to_string(), function.into()))
                    }
                    _ => None,
                }
            })
            .collect();
        Ok(Self {
            src: src.to_string(),
            tests,
        })
    }
}

impl TestSuite {
    /// Generate a test runner which can be run with python and will execute all the tests.
    /// `id` is a unique ID which will be used in the output generated by python when executing the runner.
    pub fn runner<ID: AsRef<str>>(&self, id: ID) -> String {
        let mut test_runner = String::new();
        test_runner.push_python_line(0, ["if __name__ == \"__main__\":"]);
        test_runner.push_python_line(1, ["from traceback import TracebackException"]);
        test_runner.push_python_line(1, ["import sys"]);
        self.tests.keys().for_each(|testname| {
            test_runner.push_newline();
            test_runner.push_python_line(1, ["print(\"", id.as_ref(), " ", testname, " RUNNING\")"]);
            test_runner.push_python_line( 1, ["try:"]);
            test_runner.push_python_line( 2, [testname, "()"]);
            test_runner.push_python_line( 1, ["except Exception:"]);
            test_runner.push_python_line(2,["TracebackException.from_exception(sys.exception(), capture_locals=True).print(file=sys.stdout)"]);
            test_runner.push_python_line(2,["print(\"", id.as_ref(), " ", testname, " FAIL\")"]);
            test_runner.push_python_line(1, ["else:"]);
            test_runner.push_python_line(2,["print(\"", id.as_ref(), " ", testname, " PASS\")"]);
        });
        self.src.clone() + "\n\n" + &test_runner
    }

    /// Returns an Iterator over the lines from `start` (inclusive) to `end` (exclusive)
    fn source(&self, start: &Location, end: &Location) -> impl Iterator<Item = &str> {
        let start_line = match start {
            Location::Position(pos) => self.src[0..*pos].lines().count(),
            Location::Line(_) => todo!(),
        };
        let end_line = match end {
            Location::Position(_) => todo!(),
            Location::Line(line) => *line - 1,
        };
        self.src
            .lines()
            .skip(start_line)
            .take(end_line - start_line)
    }

    /// Parse the output generated by executing the code from `runner()` and update status of all tests
    pub fn update_status(&mut self, id: &str, stdout: &str) {
        let mut tb_buf = String::new();
        for line in stdout.lines() {
            let mut words = line.split_ascii_whitespace();
            match words.next() {
                Some(id_) if id_ == id => {
                    let Some(testname) = words.next() else {
                        todo!("Make update_status fallible")
                    };
                    let Some(test) = self.tests.get_mut(testname) else {
                        todo!("Make update_status fallible")
                    };

                    match words.next() {
                        Some("PASS") => test.status = TestStatus::Pass,
                        Some("FAIL") => {
                            test.status =
                                TestStatus::Fail(tb_buf.as_str().into(), tb_buf.clone().into())
                        }
                        Some("RUNNING") => test.status = TestStatus::Running,
                        _ => todo!(),
                    }
                    tb_buf.clear();
                }
                Some(_) => {
                    tb_buf.push_line(0,[line]);
                }
                None => {todo!("Make update_status fallible")}
            }
        }
    }

    /// List all tests with status, then provide failure reports for all failed tests.
    pub fn summary_report(&self) -> String {
        let mut summary = String::new();
        let mut failures = String::new();
        for (testname, pytest) in &self.tests {
            summary.push_line(0, [testname, " ", pytest.status.as_str()]);
            if let Some(failure) = &self.failure_report(testname) {
                failures.push_newline();
                failures.push_str(failure);
            }
        }
        summary.push_str(&failures);
        summary
    }

    /// A nice extended report to make it easier to understand failed tests, similar to pytest's
    /// re-written assertions.
    pub fn failure_report(&self, testname: &str) -> Option<String> {
        enum Prefix<'str> {
            LineNumber(&'str str),
            Indent(usize),
        }

        let TestStatus::Fail(err, tb) = &self.tests[testname].status else {
            return None;
        };

        let mut frame_buf = String::new();
        match err {
            PyError::AssertionError => {
                let mut prefix = Prefix::Indent(0);
                for line in tb.lines() {
                    match line {
                        TracebackLine::TracebackHeader => (),
                        TracebackLine::FrameHeader(frameheader) => {
                            let failure =
                                Location::Line(usize::from_str(frameheader.line_number).unwrap());
                            let testfn_def =
                                Location::Position(self.tests[testname].ast.range.start().into());
                            let indent = frameheader.line_number.len() + 2;
                            frame_buf.clear();
                            frame_buf.push_line(0, ["==== ", frameheader.function_name, " ===="]);
                            for line in self.source(&testfn_def, &failure) {
                                frame_buf.push_line(indent, [line]);
                            }
                            prefix = Prefix::LineNumber(frameheader.line_number);
                        }
                        TracebackLine::FrameContents { text } => match prefix {
                            // TODO: compatibility python <3.13 ... need to manually recreate the
                            //       nice details that are in later version Tracebacks
                            Prefix::LineNumber(lineno) => {
                                frame_buf.push_line(0, [lineno, ": ", text]);
                                prefix = Prefix::Indent(lineno.len() + 2);
                            }
                            Prefix::Indent(indent) => {
                                frame_buf.push_line(indent, [text]);
                            }
                        },
                        TracebackLine::Exception(err) => {
                            frame_buf.push_line(0, [err.as_str()]);
                        }
                    }
                }
            }
            _ => todo!(),
        };
        Some(frame_buf)
    }
}

/// For incrementally generating Strings.
///
/// - Initialise with `let mut str_buf = String::(new);`
/// - Reset (contents, not capacity) with `str_buf.clear();`
/// - Extend with `push_...` functions
trait StringBuffer {
    fn push_line<'strs>(&mut self, indent: usize, contents: impl IntoIterator<Item = &'strs str>);
    fn push_python_line<'strs>(
        &mut self,
        indent: usize,
        contents: impl IntoIterator<Item = &'strs str>,
    );
    fn push_newline(&mut self);
}

impl StringBuffer for String {
    fn push_newline(&mut self) {
        self.push('\n');
    }

    /// `indent` with spaces, concatenate `contents`, end with `\n`
    fn push_line<'strs>(&mut self, indent: usize, contents: impl IntoIterator<Item = &'strs str>) {
        for _ in 0..indent {
            self.push(' ');
        }
        for text in contents {
            self.push_str(text);
        }
        self.push_newline();
    }

    /// `indent` with 4 x n spaces, concatenate `contents`, end with `\n`
    fn push_python_line<'strs>(
        &mut self,
        indent: usize,
        contents: impl IntoIterator<Item = &'strs str>,
    ) {
        self.push_line(4 * indent, contents);
    }
}

enum Location {
    Position(usize),
    Line(usize),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn one_test() {
        let src = r"def test_passes():
    assert True
";
        let pytests: TestSuite = src.try_into().unwrap();
        assert_eq!(1, pytests.tests.len());
        assert!(pytests.tests.contains_key("test_passes"));
    }

    #[test]
    fn import_and_two_tests() {
        let src = r"import pathlib


def test_fails():
    assert False


def test_passes():
    assert True
";
        let pytests: TestSuite = src.try_into().unwrap();
        assert_eq!(2, pytests.tests.len());
        assert!(pytests.tests.contains_key("test_fails"));
        assert!(pytests.tests.contains_key("test_passes"));
    }
}
