#![feature(if_let_guard)]
//! All core `pt` functionality ìs available as a library. This primarily consists of parsing and
//! report / code generation.
//!
//! Main entry point is `TestSuite`
use std::fmt::Display;

use base_traits::AsStr;
use indexmap::IndexMap;
use ruff_python_ast::Stmt;
use ruff_python_parser::{ParseError, parse_module};

mod failures;
pub use failures::{Exception, Traceback};

mod pytests;
pub use pytests::{PythonTest, TestStatus};

mod multiline;

use crate::{multiline::MultilineMut, pytests::TestDetails};

/// A suite of tests from a single python source file.
///
/// Usage:
/// ```rust
/// use pt::TestSuite;
/// let src = String::from("def test_passes():\n    assert True\n");
///
/// // Parse python source to generate a TestSuite
/// let mut tests = TestSuite::try_from(src).unwrap();
///
/// // Generate a test runner to run with python
/// let runner = tests.runner("RUNNER_1");
///
/// // Update the test status with the output from the runner
/// tests.update_status("RUNNER_1", "RUNNER_1 test_passes PASS\n");
///
/// // Generate a summary execution report
/// let summary = tests.summary_report();
/// assert_eq!("test_passes PASS\n", summary)
/// ```
#[derive(Debug, Default, PartialEq)]
pub struct TestSuite {
    src: String,
    /// indexed by test name, retains ordering from original python source
    tests: IndexMap<String, TestDetails>,
}

impl TryFrom<String> for TestSuite {
    type Error = Error;
    fn try_from(src: String) -> Result<Self, Self::Error> {
        let tests: IndexMap<String, TestDetails> = parse_module(&src)?
            .into_suite()
            .into_iter()
            .filter_map(|stmt| -> Option<(String, TestDetails)> {
                match stmt {
                    Stmt::FunctionDef(function) if function.name.as_str().starts_with("test_") => {
                        Some((function.name.to_string(), function.into()))
                    }
                    _ => None,
                }
            })
            .collect();
        Ok(Self { src, tests })
    }
}

impl TestSuite {
    /// Generate a test runner which can be run with python and will execute all the tests.
    /// `id` is a unique ID which will be used in the output generated by python when executing the runner.
    pub fn runner<ID: AsRef<str>>(&self, id: ID) -> String {
        let mut test_runner = self.src.clone();
        test_runner.push_newline();
        test_runner.push_newline();
        test_runner.push_python_line(0, ["if __name__ == \"__main__\":"]);
        test_runner.push_python_line(1, ["from traceback import TracebackException"]);
        test_runner.push_python_line(1, ["import sys"]);
        self.tests.keys().for_each(|testname| {
            test_runner.push_newline();
            test_runner.push_python_line(1, ["print(\"", id.as_ref(), " ", testname, " RUNNING\")"]);
            test_runner.push_python_line( 1, ["try:"]);
            test_runner.push_python_line( 2, [testname, "()"]);
            test_runner.push_python_line( 1, ["except Exception:"]);
            test_runner.push_python_line(2,["TracebackException.from_exception(sys.exception(), capture_locals=True).print(file=sys.stdout)"]);
            test_runner.push_python_line(2,["print(\"", id.as_ref(), " ", testname, " FAIL\")"]);
            test_runner.push_python_line(1, ["else:"]);
            test_runner.push_python_line(2,["print(\"", id.as_ref(), " ", testname, " PASS\")"]);
        });
        test_runner
    }

    /// Returns a PythonTest with non-mutable references to both the full python source text and the
    /// test details.
    pub fn test<'suite, 'name>(
        &'suite self,
        testname: &'name str,
    ) -> Option<PythonTest<'name, 'suite, 'suite>> {
        let testdetails = self.tests.get(testname)?;
        Some(PythonTest {
            testname,
            full_src: &self.src,
            test_ast: &testdetails.ast,
            status: &testdetails.status,
        })
    }

    /// Iterate over all tests.
    pub fn tests(&'_ self) -> impl Iterator<Item = PythonTest<'_, '_, '_>> {
        self.tests.iter().map(|(testname, testdetails)| PythonTest {
            testname,
            full_src: &self.src,
            test_ast: &testdetails.ast,
            status: &testdetails.status,
        })
    }

    /// Parse the output generated by executing the code from `runner()` and update status of all tests.
    /// This is potentially fallible (if the inputs are invalid). In case of error this will leave the
    /// TestSuite in an **undefined state**.
    pub fn update_status(&mut self, id: &str, stdout: &str) -> Result<(), Error> {
        let mut tb_buf = String::new();
        for line in stdout.lines() {
            let mut words = line.split_whitespace();
            match words.next() {
                Some(id_) if id_ == id => {
                    let testname = words.next().ok_or(Error::InvalidOutput)?;
                    let test = self.tests.get_mut(testname).ok_or(Error::InvalidOutput)?;
                    let status = words.next().ok_or(Error::InvalidOutput)?;
                    test.status = (status, tb_buf.as_str()).try_into()?;
                    tb_buf.clear();
                }
                _ => {
                    tb_buf.push_line(0, [line]);
                }
            }
        }
        Ok(())
    }

    /// List all tests with status, then provide failure reports for all failed tests.
    pub fn summary_report(&self) -> String {
        let mut summary = String::new();
        let mut details = String::new();
        for test in self.tests() {
            summary.push_line(0, [test.testname, " ", test.status.as_str()]);
            if let Some(report) = test.report() {
                details.push_newline();
                details.push_str(&report);
            }
        }
        summary.push_str(&details);
        summary
    }
}

#[derive(Debug)]
pub enum Error {
    InvalidTraceback,
    InvalidStatus,
    InvalidOutput,
    InvalidPython(ParseError),
}

impl From<ParseError> for Error {
    fn from(err: ParseError) -> Self {
        Self::InvalidPython(err)
    }
}

impl Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::InvalidTraceback => write!(f, "Invalid Traceback"),
            Error::InvalidStatus => write!(f, "Invalid Status"),
            Error::InvalidOutput => write!(f, "Invalid Output"),
            Error::InvalidPython(err) => write!(f, "{err}"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn one_test() {
        let src = r"def test_passes():
    assert True
";
        let pytests: TestSuite = src.to_string().try_into().unwrap();
        assert_eq!(1, pytests.tests.len());
        assert!(pytests.tests.contains_key("test_passes"));
    }

    #[test]
    fn import_and_two_tests() {
        let src = r"import pathlib


def test_fails():
    assert False


def test_passes():
    assert True
";
        let pytests: TestSuite = src.to_string().try_into().unwrap();
        assert_eq!(2, pytests.tests.len());
        assert!(pytests.tests.contains_key("test_fails"));
        assert!(pytests.tests.contains_key("test_passes"));
    }
}
